### ISSUE TITLE
Futtatás Linux alatt?

### ISSUE THREAD

**Issue by ratzalex** [daniel-randek/interju_feladat#1]
A feladatleírás az alábbiakat írja elő a programnyelvvel kapcsolatban:

"_A megoldás eredménye (az adatfeltöltő script vagy alkalmazás) lehetőleg Linux operációs rendszeren működjön, de ha ez nem megoldható, akkor a Windows is megfelel. Amennyiben Windows az operációs rendszer, úgy a futtatható adatfeltöltő (script / alkalmazás) olyan programnyelven íródjon, ami Linux-on is képes futni (pl. Python, Java. stb.). Docker-t is használhatsz._"

Ha jól látom, akkor a megoldás C#-ban készült el. Hogyan futtatható Linux OS alatt?

**Comment by daniel-randek** [comment]
Sajnos a feladatleírás erre a részére "lehetőleg Linux operációs rendszeren működjön, de ha ez nem megoldható, akkor a Windows is megfelel." koncentráltam és azt gondolotam, hogy elég ha windowson működik, ezért csináltam c#-ban. Talán valamilyen cross-platform software-framework használatával, mint például a Mono, lehetne futtatni.

A feladat pontosabb megoldása érdekében viszont csináltam egy egyszerű python nyelvű fájlt, amit ugyanebbe a repoba, a python branchbe helyeztem el script.py néven.

**Comment by ratzalex** [comment]
Rendben, köszönöm - így már Linux OS alatt is működik a megoldás.
